In [1]:
from alyx_connector import Connector

connector = Connector()

In [15]:
ihem17_sessions = connector.remote.rest(endpoint_name="sessions", action="list", subject="ihem17", details=True)
ihem17_sessions

,id,subject,start_time,number,projects,users,url,admin_url,procedures,default_data_repository,...,alias,u_alias,path,json,probe_insertion,notes,default_data_repository_path,default_data_repository_name,default_data_repository_pk,rel_path
name,,,,,,,,,,,,,,,,,,,,,
ihem17/2025-12-03/001,79907d52-6fea-4aff-9ab4-8a86fde9c258,ihem17,2025-12-03T12:30:07+01:00,1,[Interhem],"[basadipo, lpanelat]",http://127.0.0.1/api/sessions/79907d52-6fea-4a...,/admin/actions/session/79907d52-6fea-4aff-9ab4...,[Two photon Imaging],/cajal_data2/ONE/Interhem,...,ihem17/2025-12-03/001,ihem17_2025-12-03_001,/cajal_data2/ONE/Interhem/ihem17/2025-12-03/001,{'whisker_stims': {'Stimulus right': {'0': 'C2...,[],Empty DataFrame Columns: [] Index: [],/cajal_data2/ONE/Interhem,Cajal2Interhem,ea2cd868-ea54-4f59-a3b3-640130c44891,ihem17/2025-12-03/001
ihem17/2025-12-19/001,193ed528-d7a4-4d61-9543-9d939d2cfe79,ihem17,2025-12-19T12:18:59+01:00,1,[Interhem],[lpanelat],http://127.0.0.1/api/sessions/193ed528-d7a4-4d...,/admin/actions/session/193ed528-d7a4-4d61-9543...,[Two photon Imaging],/cajal_data2/ONE/Interhem,...,ihem17/2025-12-19/001,ihem17_2025-12-19_001,/cajal_data2/ONE/Interhem/ihem17/2025-12-19/001,{'whisker_stims': {'Stimulus right': {'0': 'C1...,[],Empty DataFrame Columns: [] Index: [],/cajal_data2/ONE/Interhem,Cajal2Interhem,ea2cd868-ea54-4f59-a3b3-640130c44891,ihem17/2025-12-19/001
ihem17/2025-12-02/001,92646124-5823-468f-b28e-1692326be552,ihem17,2025-12-02T14:52:04+01:00,1,[Interhem],"[basadipo, lpanelat]",http://127.0.0.1/api/sessions/92646124-5823-46...,/admin/actions/session/92646124-5823-468f-b28e...,[Two photon Imaging],/cajal_data2/ONE/Interhem,...,ihem17/2025-12-02/001,ihem17_2025-12-02_001,/cajal_data2/ONE/Interhem/ihem17/2025-12-02/001,{'whisker_stims': {'Stimulus right': {'0': 'C2...,[],Empty DataFrame Columns: [] Index: [],/cajal_data2/ONE/Interhem,Cajal2Interhem,ea2cd868-ea54-4f59-a3b3-640130c44891,ihem17/2025-12-02/001
ihem17/2026-01-16/001,e43634d7-8e49-4c9b-9d43-39071072ff7f,ihem17,2026-01-16T13:57:56+01:00,1,[Interhem],"[basadipo, lpanelat]",http://127.0.0.1/api/sessions/e43634d7-8e49-4c...,/admin/actions/session/e43634d7-8e49-4c9b-9d43...,[Two photon Imaging],/cajal_data2/ONE/Interhem,...,ihem17/2026-01-16/001,ihem17_2026-01-16_001,/cajal_data2/ONE/Interhem/ihem17/2026-01-16/001,{'whisker_stims': {'Stimulus right': {'0': 'B1...,[],user...,/cajal_data2/ONE/Interhem,Cajal2Interhem,ea2cd868-ea54-4f59-a3b3-640130c44891,ihem17/2026-01-16/001

In [6]:
sessions = connector.remote.search(details=False)
sessions

,id,subject,start_time,number,projects,users,url,admin_url,procedures,default_data_repository
name,,,,,,,,,,
ihem21/2026-01-20/001,adc46910-91c0-4879-898d-d20627599460,ihem21,2026-01-20T10:11:59+01:00,1,[Interhem],[lpanelat],http://127.0.0.1/api/sessions/adc46910-91c0-48...,/admin/actions/session/adc46910-91c0-4879-898d...,[Two photon Imaging],/cajal_data2/ONE/Interhem
ihem18/2026-01-19/001,5a42bf32-6797-4d6a-aae1-013c1da840f1,ihem18,2026-01-19T15:14:40+01:00,1,[Interhem],[lpanelat],http://127.0.0.1/api/sessions/5a42bf32-6797-4d...,/admin/actions/session/5a42bf32-6797-4d6a-aae1...,[Two photon Imaging],/cajal_data2/ONE/Interhem
ihem16/2026-01-19/001,3d12affe-8951-4c7b-ac4d-3ccef2adb568,ihem16,2026-01-19T13:21:18+01:00,1,[Interhem],[lpanelat],http://127.0.0.1/api/sessions/3d12affe-8951-4c...,/admin/actions/session/3d12affe-8951-4c7b-ac4d...,[Two photon Imaging],/cajal_data2/ONE/Interhem
ihem17/2026-01-16/001,e43634d7-8e49-4c9b-9d43-39071072ff7f,ihem17,2026-01-16T13:57:56+01:00,1,[Interhem],"[basadipo, lpanelat]",http://127.0.0.1/api/sessions/e43634d7-8e49-4c...,/admin/actions/session/e43634d7-8e49-4c9b-9d43...,[Two photon Imaging],/cajal_data2/ONE/Interhem
ihem22/2026-01-15/001,3267943b-e778-4381-b3ef-7b49d2d95b06,ihem22,2026-01-15T17:54:46+01:00,1,[Interhem],[lpanelat],http://127.0.0.1/api/sessions/3267943b-e778-43...,/admin/actions/session/3267943b-e778-4381-b3ef...,[Two photon Imaging],/cajal_data2/ONE/Interhem
...,...,...,...,...,...,...,...,...,...,...
wm9/2020-09-23/001,2e8f8e54-4af0-4c6a-9da1-81f3b833ce4b,wm9,2020-09-23T17:31:00+02:00,1,[Adaptation],[wilsonmena],http://127.0.0.1/api/sessions/2e8f8e54-4af0-4c...,/admin/actions/session/2e8f8e54-4af0-4c6a-9da1...,"[Behavior training/tasks, Two photon Imaging]",/cajal_data2/ONE/Adaptation
wm9/2020-09-22/001,24cea091-1d51-43c4-8482-78297333aa38,wm9,2020-09-22T17:31:00+02:00,1,[Adaptation],[wilsonmena],http://127.0.0.1/api/sessions/24cea091-1d51-43...,/admin/actions/session/24cea091-1d51-43c4-8482...,"[Behavior training/tasks, Two photon Imaging]",/cajal_data2/ONE/Adaptation
wm6/2020-09-22/001,31b2e3d9-c319-4c2a-875c-f31f6456c17b,wm6,2020-09-22T17:31:00+02:00,1,[Adaptation],[wilsonmena],http://127.0.0.1/api/sessions/31b2e3d9-c319-4c...,/admin/actions/session/31b2e3d9-c319-4c2a-875c...,"[Behavior training/tasks, Two photon Imaging]",/cajal_data2/ONE/Adaptation
wm9/2020-09-21/001,a5d20b4c-1295-4835-b2de-717c2ca26b61,wm9,2020-09-21T17:31:00+02:00,1,[Adaptation],[wilsonmena],http://127.0.0.1/api/sessions/a5d20b4c-1295-48...,/admin/actions/session/a5d20b4c-1295-4835-b2de...,"[Behavior training/tasks, Two photon Imaging]",/cajal_data2/ONE/Adaptation
wm6/2020-09-21/001,5c9a9206-c045-4ca9-8b37-3ddc9f3f5eaf,wm6,2020-09-21T17:31:00+02:00,1,[Adaptation],[wilsonmena],http://127.0.0.1/api/sessions/5c9a9206-c045-4c...,/admin/actions/session/5c9a9206-c045-4ca9-8b37...,"[Behavior training/tasks, Two photon Imaging]",/cajal_data2/ONE/Adaptation

In [8]:
subjects = connector.remote.search(endpoint="subjects", subject="wm36")
subjects

Loading /api/subjects/{name} details: 100%|██████████| 59/59 [00:09<00:00,  6.47it/s]

,id,nickname,url,responsible_user,birth_date,age_weeks,death_date,species,sex,litter,...,lab,genotype,description,alive,reference_weight,last_water_restriction,expected_water,remaining_water,weighings,water_administrations
name,,,,,,,,,,,,,,,,,,,,,
HaissLab__dummy,058e3ebf-2d54-451c-99a5-711190b1e3ac,dummy,http://127.0.0.1/api/subjects/HaissLab__dummy,apitsill,2023-06-19,144,None,Mus musculus,U,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__bipole3,e303df5e-649e-4bd4-a554-92628cb63d1e,bipole3,http://127.0.0.1/api/subjects/HaissLab__bipole3,wilsonmena,2022-04-06,122,2024-08-07,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],other name is bipole3 or cl01\r\npyrat id : 14...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__bipole1,08043e27-a0dc-4c15-9462-013ab1c28b03,bipole1,http://127.0.0.1/api/subjects/HaissLab__bipole1,wilsonmena,2022-04-06,122,2024-08-07,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ST...,Other name is bipole1 or wm26\r\npyrat id : 14...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ea04,b0435f65-6f6d-4c70-9548-a5d7f363b3df,ea04,http://127.0.0.1/api/subjects/HaissLab__ea04,eachirou,2023-10-15,73,2025-03-12,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 20830\r\nold mayakind id : 935876\r...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ea02,857984bf-ace8-4199-8104-68e90473567c,ea02,http://127.0.0.1/api/subjects/HaissLab__ea02,eachirou,2023-10-15,19,2024-02-27,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],old mayakind id : 935875,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ea01,638e20d3-1d52-4996-a523-c87297082a16,ea01,http://127.0.0.1/api/subjects/HaissLab__ea01,eachirou,2023-10-12,19,2024-02-23,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],old mayakind id : 933150,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem03,720b1f23-8b46-4655-8e13-e865fb715396,ihem03,http://127.0.0.1/api/subjects/HaissLab__ihem03,wilsonmena,2023-01-26,71,2024-06-06,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15548\r\nold mayakind id : 879882,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ea03,8f42996a-a23a-4b78-9d17-81833b0f91c1,ea03,http://127.0.0.1/api/subjects/HaissLab__ea03,eachirou,2023-10-12,66,2025-01-16,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 20823\r\nold mayakind id : 935859 \...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem01,5e58e5d1-2877-4543-8a76-c35c5db51dd6,ihem01,http://127.0.0.1/api/subjects/HaissLab__ihem01,wilsonmena,2023-01-26,95,2024-11-22,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15546\r\nold mayakind id : 879879,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem02,38184d5c-d0d5-4859-9d85-4442b9c58c47,ihem02,http://127.0.0.1/api/subjects/HaissLab__ihem02,wilsonmena,2023-01-26,71,2024-06-06,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15547\r\nold mayakind id : 879881,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem04,a5d50ebe-c9dc-4a93-9a6c-cca2c6a27740,ihem04,http://127.0.0.1/api/subjects/HaissLab__ihem04,wilsonmena,2023-01-26,95,2024-11-22,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15549\r\nold mayakind id : 879884,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem05,dc689aad-9b37-4fd3-831d-df278897d0a4,ihem05,http://127.0.0.1/api/subjects/HaissLab__ihem05,wilsonmena,2023-01-26,103,2025-01-16,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15551\r\nold mayakind id : 879886,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem07,fae3ea64-9a9b-4946-a161-985e456976ca,ihem07,http://127.0.0.1/api/subjects/HaissLab__ihem07,lpanelat,2024-09-12,79,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem06,279e5023-ecf1-4fa3-9c75-213169acd2ca,ihem06,http://127.0.0.1/api/subjects/HaissLab__ihem06,lpanelat,2024-09-12,79,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem10,812255ab-76c9-473c-ac2a-60e8cd0542fe,ihem10,http://127.0.0.1/api/subjects/HaissLab__ihem10,lpanelat,2024-09-12,79,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem09,34157b15-60a9-4ddc-9e24-aa82271ff690,ihem09,http://127.0.0.1/api/subjects/HaissLab__ihem09,lpanelat,2024-09-12,79,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem11,cc68e7e4-d961-41dd-a1c1-34524cba8132,ihem11,http://127.0.0.1/api/subjects/HaissLab__ihem11,lpanelat,2024-09-12,79,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_tim...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem13,e5dd032d-2fd7-461c-94e0-956926752202,ihem13,http://127.0.0.1/api/subjects/HaissLab__ihem13,lpanelat,2024-09-12,79,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_tim...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem08,98314fe5-ade3-47dc-9580-388af72582fb,ihem08,http://127.0.0.1/api/subjects/HaissLab__ihem08,lpanelat,2024-09-12,79,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,27.65,2025-06-24T15:58:14Z,0.5,0.5,subject date_tim...,subject date_tim...
HaissLab__ihem15,9e889d98-8c01-49d2-b3d1-bda04c514577,ihem15,http://127.0.0.1/api/subjects/HaissLab__ihem15,lpanelat,2025-05-16,44,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem14,d9c7a388-dd16-4a6c-a457-a308db21a460,ihem14,http://127.0.0.1/api/subjects/HaissLab__ihem14,lpanelat,2025-05-16,23,2025-10-24,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__ihem17,e90e0743-e937-43a5-9b53-8b7cc27d7292,ihem17,http://127.0.0.1/api/subjects/HaissLab__ihem17,lpanelat,2025-01-29,60,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem16,44373fac-423b-43d9-b7ac-d55d475537d7,ihem16,http://127.0.0.1/api/subjects/HaissLab__ihem16,lpanelat,2025-05-21,44,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem18,3ad92d72-82c5-43cb-9caa-c6a79a361ebf,ihem18,http://127.0.0.1/api/subjects/HaissLab__ihem18,lpanelat,2025-01-29,60,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],FOHA-00388,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem12,fa17b622-32b3-4afa-82a0-d30e165e57a9,ihem12,http://127.0.0.1/api/subjects/HaissLab__ihem12,lpanelat,2024-09-12,79,None,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,30.50,2025-06-24T16:04:56Z,0.5,0.5,subject date_tim...,subject date_tim...
HaissLab__ihem19,6b80b214-8a32-437b-9b85-b8516f9efced,ihem19,http://127.0.0.1/api/subjects/HaissLab__ihem19,lpanelat,2025-05-16,44,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem20,c2224173-9d28-4036-a81e-522ca177ab49,ihem20,http://127.0.0.1/api/subjects/HaissLab__ihem20,lpanelat,2025-06-07,41,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem21,537a43c1-f0e9-46b9-838a-ae292352d83b,ihem21,http://127.0.0.1/api/subjects/HaissLab__ihem21,lpanelat,2025-06-07,41,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__ihem22,6ccf9ba2-a1a4-4dc3-a2f7-21cd5f144d24,ihem22,http://127.0.0.1/api/subjects/HaissLab__ihem22,lpanelat,2025-06-07,41,None,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Camk2a-tTA : Tg/+\r\ntetO-GCaMP6s : Tg/+,True,0.00,None,0.5,0.5,subject date_time...,Empty DataFrame Columns: [] Index: []
HaissLab__jedi01,3e4faed1-9b37-4ff3-a089-a635ca6b1079,jedi01,http://127.0.0.1/api/subjects/HaissLab__jedi01,wilsonmena,2023-01-26,110,2025-03-12,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15550\r\nold mayakind id : 879885,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__jedi02,de3e94d3-2455-4f05-ba1d-d98d34dbd977,jedi02,http://127.0.0.1/api/subjects/HaissLab__jedi02,wilsonmena,2022-12-06,81,2024-06-27,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15282\r\nold mayakind id : 871428,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__test_mouse,9efbe205-ca10-4956-948e-7d28869690e2,test_mouse,http://127.0.0.1/api/subjects/HaissLab__test_m...,task_bot,2023-08-01,138,None,Mus musculus,U,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],This is a test animal,True,28.00,None,0.5,0.5,subject date_...,Empty DataFrame Columns: [] Index: []
HaissLab__wm6,c01fa1a0-79ba-4138-ae25-b247cce4769d,wm6,http://127.0.0.1/api/subjects/HaissLab__wm6,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm7,8d52c10e-6b21-4068-89bb-03c1693bb261,wm7,http://127.0.0.1/api/subjects/HaissLab__wm7,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm9,b2f6cc55-f668-482c-bfd7-f8066218f384,wm9,http://127.0.0.1/api/subjects/HaissLab__wm9,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm11,9bbf8571-ea3b-4ae4-a329-e5937de82a49,wm11,http://127.0.0.1/api/subjects/HaissLab__wm11,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm10,eddd0e35-554c-4972-853b-db2fbac06c9c,wm10,http://127.0.0.1/api/subjects/HaissLab__wm10,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm13,2c480854-8f1f-40ab-b3eb-b7227018ea66,wm13,http://127.0.0.1/api/subjects/HaissLab__wm13,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm18,0c49f00f-7b70-4940-b247-b9b73517dbf8,wm18,http://127.0.0.1/api/subjects/HaissLab__wm18,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm24,e4a8c4d4-e521-4459-bfe1-88e258595ad1,wm24,http://127.0.0.1/api/subjects/HaissLab__wm24,wilsonmena,None,0,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm25,1c2929f5-f658-466d-b1fa-e317df9fecfa,wm25,http://127.0.0.1/api/subjects/HaissLab__wm25,wilsonmena,2022-11-28,7,2023-01-17,Mus musculus,U,None,...,HaissLab,allele zygosity 0 ST...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm27,5373513c-fd5d-4d23-ad14-e8d8ba6fd69b,wm27,http://127.0.0.1/api/subjects/HaissLab__wm27,wilsonmena,2022-10-05,90,2024-06-27,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Other name is bipole2\r\npyrat id : 15076\r\no...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm28,70b2963f-b378-4d67-a7a1-0c5989e8ce76,wm28,http://127.0.0.1/api/subjects/HaissLab__wm28,wilsonmena,2021-08-31,108,2023-09-28,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],This is the Interhemichperic Animal number 00\...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm29,e8e4c137-3857-462a-a90b-50c8fbc6bffa,wm29,http://127.0.0.1/api/subjects/HaissLab__wm29,wilsonmena,2022-03-17,85,2023-11-02,Mus musculus,M,None,...,HaissLab,allele zygosity 0 ...,Animalerie name : VGAT-JRGECO nb 26\r\nAnimale...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm31,562e134d-8e85-4536-ad9a-c64ac830eacd,wm31,http://127.0.0.1/api/subjects/HaissLab__wm31,wilsonmena,2022-04-06,82,2023-11-02,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie name : VGAT-JRGECO nb 28\r\nAnimale...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm32,b4082bf2-1df4-40ce-9fff-5e84d5dc74fe,wm32,http://127.0.0.1/api/subjects/HaissLab__wm32,wilsonmena,2022-03-17,109,2024-04-23,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],The name in the animalerie system is VGAT#29\r...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm33,b37c8df8-ecb2-4d28-9d9d-025be55d27cb,wm33,http://127.0.0.1/api/subjects/HaissLab__wm33,wilsonmena,2022-04-06,113,2024-06-06,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],"In the animalerie system, this mouse is the mo...",False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm34,8036752b-622f-4efd-9bda-0f8baeb3103f,wm34,http://127.0.0.1/api/subjects/HaissLab__wm34,wilsonmena,2023-04-09,63,2024-06-27,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904175,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm35,6a38aa8b-401e-430f-9722-ef97fbda2409,wm35,http://127.0.0.1/api/subjects/HaissLab__wm35,wilsonmena,2023-04-09,54,2024-04-23,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904164,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm30,0b56ae82-bc76-4fe7-8d60-cf5e470116f4,wm30,http://127.0.0.1/api/subjects/HaissLab__wm30,wilsonmena,2022-04-06,113,2024-06-06,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ...,Animalerie name : VGAT-JRGECO nb 27\r\nAnimale...,False,25.00,None,1.2,1.2,subject date_time ...,subject date_time ...
HaissLab__wm37,82c44b51-6fa8-4ce1-8a0b-d3f6f1caf58f,wm37,http://127.0.0.1/api/subjects/HaissLab__wm37,wilsonmena,2023-04-09,54,2024-04-23,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 16874\r\nmayakind id : 904162,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm38,95ff4111-7d37-4e64-bbc3-95e43acbef8b,wm38,http://127.0.0.1/api/subjects/HaissLab__wm38,wilsonmena,2023-04-09,54,2024-04-23,Mus musculus,F,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 16873\r\nold mayakind id : 904161,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm36,225a9d42-8294-4af7-a476-6f34491cdf1d,wm36,http://127.0.0.1/api/subjects/HaissLab__wm36,wilsonmena,2023-04-09,92,2025-01-16,Mus musculus,M,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904174,False,27.00,None,0.5,0.5,subject date_time ...,subject date_time ...
HaissLab__wm39,04d07c68-649d-4ee3-95d3-e049a67ceab8,wm39,http://127.0.0.1/api/subjects/HaissLab__wm39,wilsonmena,2024-09-11,80,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ...,Pyrat id : FOHA-00325,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm40,50fbc4e5-7ff3-4e68-92a7-777c40810a43,wm40,http://127.0.0.1/api/subjects/HaissLab__wm40,wilsonmena,2024-09-11,80,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ST...,Pyrat id : FOHA-00323,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm41,7beb5743-3742-4372-9451-310283671bb3,wm41,http://127.0.0.1/api/subjects/HaissLab__wm41,wilsonmena,2024-09-11,80,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ...,Pyrat id : FOHA-00326,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm42,d1e9dd22-f544-4952-af93-5956e455f0f2,wm42,http://127.0.0.1/api/subjects/HaissLab__wm42,wilsonmena,2024-09-11,80,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 ...,Pyrat id : FOHA-00324,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm43,db479299-caac-44ed-baf5-b6f653053502,wm43,http://127.0.0.1/api/subjects/HaissLab__wm43,wilsonmena,2024-03-13,106,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 Camk2a-tTA ...,pyrat id : FOHA-00147,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
HaissLab__wm44,5272ddba-897a-48ce-a31b-f8e2fba3e522,wm44,http://127.0.0.1/api/subjects/HaissLab__wm44,wilsonmena,2024-03-13,106,None,Mus musculus,F,None,...,HaissLab,allele zygosity 0 Camk2a-tTA ...,,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []

In [11]:
connector.remote.authenticator.is_authenticated()

True

In [13]:
connector.remote.search(name="ea04/2024-09-30/001")

id                                           4ac87ea1-f8f6-4ac2-b773-fa87fba11ccc
subject                                                                      ea04
users                                                                  [eachirou]
location                                                                     None
procedures                                                   [Two photon Imaging]
lab                                                                      HaissLab
projects                                                             [MotorSense]
type                                                                         None
task_protocol
number                                                                          1
start_time                                              2024-09-30T17:50:00+02:00
end_time                                                2024-09-30T18:20:00+02:00
narrative                       Whiskers stimulated:\r\n- C2: right\r\n- C3: l...
parent_session                                                               None
n_correct_trials                                                             None
n_trials                                                                     None
url                             http://127.0.0.1/api/sessions/4ac87ea1-f8f6-4a...
extended_qc                                                                  None
qc                                                                              0
wateradmin_session_related                                                     []
data_dataset_session_related    [{'id': 'c83eb10a-7db8-423c-8cee-31b733dc27d2'...
auto_datetime                                    2024-10-01T17:49:44.719005+02:00
alias                                                         ea04/2024-09-30/001
u_alias                                                       ea04_2024-09-30_001
path                              /cajal_data2/ONE/MotorSense/ea04/2024-09-30/001
json                            {'whisker_stims': {'Stimulus right': {'0': 'C3...
probe_insertion                                                                []
notes                                                                          []
default_data_repository_path                          /cajal_data2/ONE/MotorSense
default_data_repository_name                                     Cajal2MotorSense
default_data_repository_pk                   70a43e0f-09b3-4c0f-996c-12edbdaff06d
rel_path                                                      ea04/2024-09-30/001
admin_url                       /admin/actions/session/4ac87ea1-f8f6-4ac2-b773...
Name: ea04/2024-09-30/001, dtype: object