In [1]:
from alyx_connector import Connector
connector = Connector()

In [2]:
connector.web_client.list_endpoints()

['/api/auth-token',
 '/api/brain-regions',
 '/api/brain-regions/{id}',
 '/api/cache.zip',
 '/api/cache/info/',
 '/api/channels',
 '/api/channels/{id}',
 '/api/data-formats',
 '/api/data-formats/{name}',
 '/api/data-repository',
 '/api/data-repository-type',
 '/api/data-repository-type/{name}',
 '/api/data-repository/{name}',
 '/api/dataset-types',
 '/api/dataset-types/{name}',
 '/api/datasets',
 '/api/datasets/{id}',
 '/api/downloads',
 '/api/downloads/{id}',
 '/api/files',
 '/api/files/{id}',
 '/api/insertions',
 '/api/insertions/{id}',
 '/api/labs',
 '/api/labs/{name}',
 '/api/locations',
 '/api/locations/{name}',
 '/api/media/{img_url}',
 '/api/new-download',
 '/api/notes',
 '/api/notes/{id}',
 '/api/procedures',
 '/api/projects',
 '/api/projects/{name}',
 '/api/register-file',
 '/api/revisions',
 '/api/revisions/{name}',
 '/api/server-info',
 '/api/sessions',
 '/api/sessions/{id}',
 '/api/sessions/{name}',
 '/api/subjects',
 '/api/subjects/{nickname}',
 '/api/surgeries',
 '/api/sync-file-status',
 '/api/tags',
 '/api/tags/{id}',
 '/api/tasks',
 '/api/tasks/{id}',
 '/api/trajectories',
 '/api/trajectories/{id}',
 '/api/users',
 '/api/users/{username}',
 '/api/water-administrations',
 '/api/water-administrations/{id}',
 '/api/water-requirement/{nickname}',
 '/api/water-restricted-subjects',
 '/api/water-restriction',
 '/api/water-type',
 '/api/water-type/{name}',
 '/api/weighings',
 '/api/weighings/{id}']

In [11]:
all_mice = connector.web_client.rest(endpoint_name="sessions", action="list", subject="ihem")
all_mice

,id,subject,start_time,number,projects,users,url,admin_url,procedures,default_data_repository
name,,,,,,,,,,
,ebecd55f-a8d7-4d93-890e-3cbc47c60f7c,ihem,2025-12-15T12:00:00+01:00,2,[TestProject],[admin],http://127.0.0.1/sessions/ebecd55f-a8d7-4d93-8...,/admin/actions/session/ebecd55f-a8d7-4d93-890e...,[Behaviour Imaging],//127.0.0.1/here/test

In [ ]:
all_mice

Empty DataFrame
Columns: []
Index: []

In [8]:
sessions = connector.search()

Loading <alyx_connector.web.api.Endpoint object at 0x7ba887ebc0b0> details:  49%|████▊     | 485/999 [1:26:35<1:31:46, 10.71s/it]

KeyboardInterrupt:

In [6]:
sessions = connector.search(endpoint="subjects", subject="wm36")

Loading <alyx_connector.web.api.Endpoint object at 0x7ba887ea3d70> details: 100%|██████████| 59/59 [00:08<00:00,  6.76it/s]

In [7]:
sessions

,id,url,responsible_user,birth_date,age_weeks,death_date,species,sex,litter,strain,...,lab,genotype,description,alive,reference_weight,last_water_restriction,expected_water,remaining_water,weighings,water_administrations
nickname,,,,,,,,,,,,,,,,,,,,,
ea01,638e20d3-1d52-4996-a523-c87297082a16,http://127.0.0.1/api/subjects/ea01,eachirou,2023-10-12,19,2024-02-23,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],old mayakind id : 933150,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
dummy,058e3ebf-2d54-451c-99a5-711190b1e3ac,http://127.0.0.1/api/subjects/dummy,apitsill,2023-06-19,135,None,Laboratory mouse,U,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
bipole3,e303df5e-649e-4bd4-a554-92628cb63d1e,http://127.0.0.1/api/subjects/bipole3,wilsonmena,2022-04-06,122,2024-08-07,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],other name is bipole3 or cl01\r\npyrat id : 14...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
bipole1,08043e27-a0dc-4c15-9462-013ab1c28b03,http://127.0.0.1/api/subjects/bipole1,wilsonmena,2022-04-06,122,2024-08-07,Laboratory mouse,F,None,C57BL/6J,...,HaissLab,allele zygosity 0 VGAT>Cr...,Other name is bipole1 or wm26\r\npyrat id : 14...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ea02,857984bf-ace8-4199-8104-68e90473567c,http://127.0.0.1/api/subjects/ea02,eachirou,2023-10-15,19,2024-02-27,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],old mayakind id : 935875,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ea03,8f42996a-a23a-4b78-9d17-81833b0f91c1,http://127.0.0.1/api/subjects/ea03,eachirou,2023-10-12,66,2025-01-16,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 20823\r\nold mayakind id : 935859 \...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem02,38184d5c-d0d5-4859-9d85-4442b9c58c47,http://127.0.0.1/api/subjects/ihem02,wilsonmena,2023-01-26,71,2024-06-06,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15547\r\nold mayakind id : 879881,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem03,720b1f23-8b46-4655-8e13-e865fb715396,http://127.0.0.1/api/subjects/ihem03,wilsonmena,2023-01-26,71,2024-06-06,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15548\r\nold mayakind id : 879882,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ea04,b0435f65-6f6d-4c70-9548-a5d7f363b3df,http://127.0.0.1/api/subjects/ea04,eachirou,2023-10-15,73,2025-03-12,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 20830\r\nold mayakind id : 935876\r...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem01,5e58e5d1-2877-4543-8a76-c35c5db51dd6,http://127.0.0.1/api/subjects/ihem01,wilsonmena,2023-01-26,95,2024-11-22,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15546\r\nold mayakind id : 879879,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem04,a5d50ebe-c9dc-4a93-9a6c-cca2c6a27740,http://127.0.0.1/api/subjects/ihem04,wilsonmena,2023-01-26,95,2024-11-22,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyRatId: 15549\r\nold mayakind id : 879884,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem05,dc689aad-9b37-4fd3-831d-df278897d0a4,http://127.0.0.1/api/subjects/ihem05,wilsonmena,2023-01-26,103,2025-01-16,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15551\r\nold mayakind id : 879886,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem06,279e5023-ecf1-4fa3-9c75-213169acd2ca,http://127.0.0.1/api/subjects/ihem06,lpanelat,2024-09-12,70,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem09,34157b15-60a9-4ddc-9e24-aa82271ff690,http://127.0.0.1/api/subjects/ihem09,lpanelat,2024-09-12,70,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem10,812255ab-76c9-473c-ac2a-60e8cd0542fe,http://127.0.0.1/api/subjects/ihem10,lpanelat,2024-09-12,70,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem07,fae3ea64-9a9b-4946-a161-985e456976ca,http://127.0.0.1/api/subjects/ihem07,lpanelat,2024-09-12,70,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem11,cc68e7e4-d961-41dd-a1c1-34524cba8132,http://127.0.0.1/api/subjects/ihem11,lpanelat,2024-09-12,70,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem13,e5dd032d-2fd7-461c-94e0-956926752202,http://127.0.0.1/api/subjects/ihem13,lpanelat,2024-09-12,70,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem08,98314fe5-ade3-47dc-9580-388af72582fb,http://127.0.0.1/api/subjects/ihem08,lpanelat,2024-09-12,70,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,27.65,2025-06-24T15:58:14Z,0.5,0.5,subject date_time weight ...,subject date_time water_a...
ihem14,d9c7a388-dd16-4a6c-a457-a308db21a460,http://127.0.0.1/api/subjects/ihem14,lpanelat,2025-05-16,23,2025-10-24,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem15,9e889d98-8c01-49d2-b3d1-bda04c514577,http://127.0.0.1/api/subjects/ihem15,lpanelat,2025-05-16,35,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
ihem16,44373fac-423b-43d9-b7ac-d55d475537d7,http://127.0.0.1/api/subjects/ihem16,lpanelat,2025-05-21,34,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem17,e90e0743-e937-43a5-9b53-8b7cc27d7292,http://127.0.0.1/api/subjects/ihem17,lpanelat,2025-01-29,50,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem12,fa17b622-32b3-4afa-82a0-d30e165e57a9,http://127.0.0.1/api/subjects/ihem12,lpanelat,2024-09-12,70,None,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,30.50,2025-06-24T16:04:56Z,0.5,0.5,subject date_time weight ...,subject date_time water_a...
ihem18,3ad92d72-82c5-43cb-9caa-c6a79a361ebf,http://127.0.0.1/api/subjects/ihem18,lpanelat,2025-01-29,50,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],FOHA-00388,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem19,6b80b214-8a32-437b-9b85-b8516f9efced,http://127.0.0.1/api/subjects/ihem19,lpanelat,2025-05-16,35,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem20,c2224173-9d28-4036-a81e-522ca177ab49,http://127.0.0.1/api/subjects/ihem20,lpanelat,2025-06-07,32,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem21,537a43c1-f0e9-46b9-838a-ae292352d83b,http://127.0.0.1/api/subjects/ihem21,lpanelat,2025-06-07,32,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
ihem22,6ccf9ba2-a1a4-4dc3-a2f7-21cd5f144d24,http://127.0.0.1/api/subjects/ihem22,lpanelat,2025-06-07,32,None,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Camk2a-tTA : Tg/+\r\ntetO-GCaMP6s : Tg/+,True,0.00,None,0.5,0.5,subject date_time weight ...,Empty DataFrame Columns: [] Index: []
jedi01,3e4faed1-9b37-4ff3-a089-a635ca6b1079,http://127.0.0.1/api/subjects/jedi01,wilsonmena,2023-01-26,110,2025-03-12,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15550\r\nold mayakind id : 879885,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
jedi02,de3e94d3-2455-4f05-ba1d-d98d34dbd977,http://127.0.0.1/api/subjects/jedi02,wilsonmena,2022-12-06,81,2024-06-27,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 15282\r\nold mayakind id : 871428,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
test_mouse,9efbe205-ca10-4956-948e-7d28869690e2,http://127.0.0.1/api/subjects/test_mouse,task_bot,2023-08-01,129,None,Laboratory mouse,U,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],This is a test animal,True,28.00,None,0.5,0.5,subject date_time weig...,Empty DataFrame Columns: [] Index: []
wm6,c01fa1a0-79ba-4138-ae25-b247cce4769d,http://127.0.0.1/api/subjects/wm6,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm7,8d52c10e-6b21-4068-89bb-03c1693bb261,http://127.0.0.1/api/subjects/wm7,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm9,b2f6cc55-f668-482c-bfd7-f8066218f384,http://127.0.0.1/api/subjects/wm9,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm10,eddd0e35-554c-4972-853b-db2fbac06c9c,http://127.0.0.1/api/subjects/wm10,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm11,9bbf8571-ea3b-4ae4-a329-e5937de82a49,http://127.0.0.1/api/subjects/wm11,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm13,2c480854-8f1f-40ab-b3eb-b7227018ea66,http://127.0.0.1/api/subjects/wm13,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm18,0c49f00f-7b70-4940-b247-b9b73517dbf8,http://127.0.0.1/api/subjects/wm18,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm24,e4a8c4d4-e521-4459-bfe1-88e258595ad1,http://127.0.0.1/api/subjects/wm24,wilsonmena,None,0,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm25,1c2929f5-f658-466d-b1fa-e317df9fecfa,http://127.0.0.1/api/subjects/wm25,wilsonmena,2022-11-28,7,2023-01-17,Laboratory mouse,U,None,C57BL/6J,...,HaissLab,allele zygosity 0 VGAT>Cre ...,,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm27,5373513c-fd5d-4d23-ad14-e8d8ba6fd69b,http://127.0.0.1/api/subjects/wm27,wilsonmena,2022-10-05,90,2024-06-27,Laboratory mouse,M,None,C57BL/6J,...,HaissLab,Empty DataFrame Columns: [] Index: [],Other name is bipole2\r\npyrat id : 15076\r\no...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm28,70b2963f-b378-4d67-a7a1-0c5989e8ce76,http://127.0.0.1/api/subjects/wm28,wilsonmena,2021-08-31,108,2023-09-28,Laboratory mouse,F,None,C57BL/6J,...,HaissLab,Empty DataFrame Columns: [] Index: [],This is the Interhemichperic Animal number 00\...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm29,e8e4c137-3857-462a-a90b-50c8fbc6bffa,http://127.0.0.1/api/subjects/wm29,wilsonmena,2022-03-17,85,2023-11-02,Laboratory mouse,M,None,None,...,HaissLab,allele zygosity 0 AAV-jRGECO ...,Animalerie name : VGAT-JRGECO nb 26\r\nAnimale...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm31,562e134d-8e85-4536-ad9a-c64ac830eacd,http://127.0.0.1/api/subjects/wm31,wilsonmena,2022-04-06,82,2023-11-02,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie name : VGAT-JRGECO nb 28\r\nAnimale...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm32,b4082bf2-1df4-40ce-9fff-5e84d5dc74fe,http://127.0.0.1/api/subjects/wm32,wilsonmena,2022-03-17,109,2024-04-23,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],The name in the animalerie system is VGAT#29\r...,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm30,0b56ae82-bc76-4fe7-8d60-cf5e470116f4,http://127.0.0.1/api/subjects/wm30,wilsonmena,2022-04-06,113,2024-06-06,Laboratory mouse,F,None,None,...,HaissLab,allele zygosity 0 AAV-GFP<Cre ...,Animalerie name : VGAT-JRGECO nb 27\r\nAnimale...,False,25.00,None,1.2,1.2,subject date_time weight ...,subject date_time water_ad...
wm33,b37c8df8-ecb2-4d28-9d9d-025be55d27cb,http://127.0.0.1/api/subjects/wm33,wilsonmena,2022-04-06,113,2024-06-06,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],"In the animalerie system, this mouse is the mo...",False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm34,8036752b-622f-4efd-9bda-0f8baeb3103f,http://127.0.0.1/api/subjects/wm34,wilsonmena,2023-04-09,63,2024-06-27,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904175,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm35,6a38aa8b-401e-430f-9722-ef97fbda2409,http://127.0.0.1/api/subjects/wm35,wilsonmena,2023-04-09,54,2024-04-23,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904164,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm38,95ff4111-7d37-4e64-bbc3-95e43acbef8b,http://127.0.0.1/api/subjects/wm38,wilsonmena,2023-04-09,54,2024-04-23,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 16873\r\nold mayakind id : 904161,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm37,82c44b51-6fa8-4ce1-8a0b-d3f6f1caf58f,http://127.0.0.1/api/subjects/wm37,wilsonmena,2023-04-09,54,2024-04-23,Laboratory mouse,F,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],pyrat id : 16874\r\nmayakind id : 904162,False,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm36,225a9d42-8294-4af7-a476-6f34491cdf1d,http://127.0.0.1/api/subjects/wm36,wilsonmena,2023-04-09,92,2025-01-16,Laboratory mouse,M,None,None,...,HaissLab,Empty DataFrame Columns: [] Index: [],Animalerie id : 904174,False,27.00,None,0.5,0.5,subject date_time weight ...,subject date_time water_ad...
wm39,04d07c68-649d-4ee3-95d3-e049a67ceab8,http://127.0.0.1/api/subjects/wm39,wilsonmena,2024-09-11,70,None,Laboratory mouse,F,None,Agouti,...,HaissLab,allele zygosity 0 AAV-jRGECO ...,Pyrat id : FOHA-00325,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm40,50fbc4e5-7ff3-4e68-92a7-777c40810a43,http://127.0.0.1/api/subjects/wm40,wilsonmena,2024-09-11,70,None,Laboratory mouse,F,None,Agouti,...,HaissLab,allele zygosity 0 VGAT>Cre ...,Pyrat id : FOHA-00323,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm41,7beb5743-3742-4372-9451-310283671bb3,http://127.0.0.1/api/subjects/wm41,wilsonmena,2024-09-11,70,None,Laboratory mouse,F,None,Agouti,...,HaissLab,allele zygosity 0 AAV-jRGECO ...,Pyrat id : FOHA-00326,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm42,d1e9dd22-f544-4952-af93-5956e455f0f2,http://127.0.0.1/api/subjects/wm42,wilsonmena,2024-09-11,70,None,Laboratory mouse,F,None,Agouti,...,HaissLab,allele zygosity 0 AAV-jRGECO ...,Pyrat id : FOHA-00324,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm43,db479299-caac-44ed-baf5-b6f653053502,http://127.0.0.1/api/subjects/wm43,wilsonmena,2024-03-13,96,None,Laboratory mouse,F,None,C57BL/6J,...,HaissLab,allele zygosity 0 Camk2a-tTA ...,pyrat id : FOHA-00147,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []
wm44,5272ddba-897a-48ce-a31b-f8e2fba3e522,http://127.0.0.1/api/subjects/wm44,wilsonmena,2024-03-13,96,None,Laboratory mouse,F,None,C57BL/6J,...,HaissLab,allele zygosity 0 Camk2a-tTA ...,,True,0.00,None,0.5,0.5,Empty DataFrame Columns: [] Index: [],Empty DataFrame Columns: [] Index: []

In [2]:
connector.web_client.is_logged_in()

True

In [11]:
connector.search(name="ea04/2024-09-30/001")

subject                                                                      ea04
users                                                                  [eachirou]
location                                                                     None
procedures                                                   [Two photon Imaging]
lab                                                                      HaissLab
projects                                                             [MotorSense]
type                                                                         None
task_protocol
number                                                                          1
start_time                                              2024-09-30T17:50:00+02:00
end_time                                                2024-09-30T18:20:00+02:00
narrative                       Whiskers stimulated:\r\n- C2: right\r\n- C3: l...
parent_session                                                               None
n_correct_trials                                                             None
n_trials                                                                     None
url                             http://127.0.0.1/sessions/4ac87ea1-f8f6-4ac2-b...
extended_qc                                                                  None
qc                                                                        NOT_SET
wateradmin_session_related                                                     []
data_dataset_session_related    [{'id': '9bbddde0-8918-4826-a527-0e29f9312d92'...
auto_datetime                                    2024-10-01T17:49:44.719005+02:00
alias                                                         ea04/2024-09-30/001
u_alias                                                       ea04_2024-09-30_001
path                            //157.99.138.167/cajal_data2/ONE/MotorSense/ea...
name                                                          ea04/2024-09-30/001
json                            {'whisker_stims': {'Stimulus right': {'0': 'C3...
probe_insertion                                                                []
notes                                                                          []
default_data_repository_path          //157.99.138.167/cajal_data2/ONE/MotorSense
default_data_repository_name                                     Cajal2MotorSense
default_data_repository_pk                   70a43e0f-09b3-4c0f-996c-12edbdaff06d
rel_path                                                      ea04/2024-09-30/001
admin_url                       /admin/actions/session/4ac87ea1-f8f6-4ac2-b773...
Name: 4ac87ea1-f8f6-4ac2-b773-fa87fba11ccc, dtype: object

In [12]:
session = sessions.iloc[3] # getting the third session obtained, by index
print(session.narrative) # printing the narrative of the session

- Vgat#33 / wm#36_20230929
- Folder/Session: 001
- B1 (left)
- Beta (right)
- PW: 10 to 90 Hz and AW: 0 Hz or 10 Hz
- PW: 10 to 20 Hz and AW: 0 Hz or 10 Hz
- PW: 10           Hz and AW: 0 Hz or 10 Hz
- Rotation: 18
- zoom: 1.8
- awake mice
- FOV (Session 5)
- pupil recorded
- whisker recorded

Note:
- pupil recording is interrupted at trial #291
- whisker recording is interrupted at trial #291
- 2P continue without problems

In [13]:
session.json # session.json is a dictionnary or list (potentially nested)

{'whisker_stims': {'amplitudes': {'abstract': ['10-0',
    '10-10',
    '10_20-0',
    '10_20-10',
    '10_90-0',
    '10_90-10'],
   'side_aware': ['left_10-right_0',
    'left_10-right_10',
    'left_10_20-right_0',
    'left_10_20-right_10',
    'left_10_90-right_0',
    'left_10_90-right_10',
    'right_10-left_0',
    'right_10-left_10',
    'right_10_20-left_0',
    'right_10_20-left_10',
    'right_10_90-left_0',
    'right_10_90-left_10']},
  'Stimulus right': {'0': 'B1', '1': 'Beta'}},
 '2p_acquisition': {'zoom_factor': 1.8}}

In [14]:
session.json["whisker_stims"]["Stimulus right"]["1"] # you can access it's content like a standard dictionnary

'Beta'